export const ListaProdutos = [
  {
    id: 1,
    img: "../public/celular1.png",
    preco: "R$ 1.000,00",
    armaz: "128GB",
    marca: "../public/apple.png",
    modelo: "Iphone 12",
    cores: "Preto, Branco, Vermelho, Azul, Verde",
  },
  {
    id: 2,
    img: "../public/celular2.png",
    preco: "R$ 1.200,00",
    armaz: "256GB",
    marca: "../public/apple.png",
    modelo: "iPhone 12 Pro",
    cores: "Cinza Espacial, Prata, Ouro, Azul Pacífico",
  },
  {
    id: 3,
    img: "../public/celular3.jpg",
    preco: "R$ 1.500,00",
    armaz: "512GB",
    marca: "../public/apple.png",
    modelo: "iPhone 14 Pro Max",
    cores: "Grafite, Prata, Ouro, Azul Pacífico",
  },
  {
    id: 4,
    img: "../public/celular4.PNG",
    preco: "R$ 900,00",
    armaz: "128GB",
    marca: "../public/samsung.png",
    modelo: "Galaxy S21",
    cores: "Phantom Gray, Phantom White, Phantom Violet",
  },
  {
    id: 5,
    img: "../public/celular5.jpg",
    preco: "R$ 1.100,00",
    armaz: "256GB",
    marca: "../public/samsung.png",
    modelo: "Galaxy S21 Ultra",
    cores: "Phantom Black, Phantom Silver",
  },
  {
    id: 6,
    img: "../public/celular6.png",
    preco: "R$ 1.800,00",
    armaz: "1TB",
    marca: "../public/apple.png",
    modelo: "iPhone XR",
    cores: "Graphite, Gold, Silver, Sierra Blue",
  },
];
